on: push
name: deploy
jobs:
        deploy:
                name: deploy to cluster
                runs-on: ubuntu-20.04
                steps:
                        - uses: actions/checkout@master
                        - name: login to dockerhub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_PASSWORD }}
                        - name: build and push to docker
                          uses: docker/build-push-action@v2
                          with: # acciones del step docker build-push-action
                                  push: true
                                  repository: ${{ github.repository }}
                                  tag_with_ref: true
                                  tag_with_sha: true
                                  tags: user/${{ github.sha }}
                                  #                        - name: deploy to cluster
                                  #                          uses: steebchen/kubectl@master
                                  #                          env:
                                  #                                  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
                                  #                          with:
                                  #                                  args: set image --record deployment/my-app prueba-gha=${{ github.repository }}:${{  }}
                                  #                        - name: verify deployment
                                  #                          uses: steebchen/kubectl@master
                                  #                          env:
                                  #                                  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
                                  #                                  KUBECTL_VERSION: "1.15"
                                  #                          with:
                                  #                                  args: '"rollout status deployment/my-app"'

